### ISSUE TITLE
Standard Library implementation tracker

### ISSUE THREAD

**Issue by HyperCodec** [HyperCodec/zisp#10]
Comments should include features to include in STD.

**Comment by HyperCodec** [comment]
- [ ] `execute arg1` - Runs terminal command of arg1. Potentially could go for `execute arg1 list1` for individual arguments as a list.
- [ ] `eval arg1` - Runs zisp code as a string.

**Comment by HyperCodec** [comment]
#7 should be complete before I start working on stuff from this issue

**Comment by HyperCodec** [comment]
- [ ] `printf format arg1 arg2  ...` - Formats characters into a string.
- [ ] `printfln format arg1 arg2 ...` - Essentially `printf` but with a newline.
